### ISSUE TITLE
local-ga.js is empty

### ISSUE THREAD

**Issue by mulsun** [hosting-io/wp-disable#6]
local-ga.js is empty, the script is not loaded. Tried on two different WP set ups, had the same result. I have put the plugin off and on, tried to update the GA details on dashboard, changed FTP permissions, nothing seems like helping it so far.

**Comment by FoliumStudio** [comment]
Hi, GA is a known issue, its not on every server, but some just seem to not work, the only advice we can offer is to not use the GA function in these cases
